# Generated by Django 3.1.3 on 2021-06-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='complete',
        ),
    ]
